const mongoose = require("mongoose");

const laptopSchema = new mongoose.Schema({
  brand: String,
  model_code: String,
  product_name: String,
  color: String,
  price_rm: Number,
  imageURL: String,
  copilot_support: { type: Boolean, default: false },
  processor_name: String,
  processor_brand: String,
  processor_ghz: Number,
  cpu_benchmark: Number,
  ram_gb: Number,
  ram_type: String,
  display_type: String,
  display_resolution: String,
  display_size_inch: Number,
  display_refresh_rate_hz: Number,
  gpu_model: String,
  gpu_brand: String,
  gpu_benchmark: Number,
  ssd_gb: Number,
  ssd_type: String,
  io_ports: String,
  network: String,
  bluetooth: String,
  power_supply: String,
  battery_capacity_wh: Number,
  dimension_cm: String,
  weight_kg: Number,
  bundle: String,
  microsoft_office: String,
  warranty: String,
  release_year: Number,
  expansion_slots: String,
  os: String,
});

module.exports = mongoose.model("Laptop", laptopSchema);
